### ISSUE TITLE
About action detection with proposals

### ISSUE THREAD

**Issue by coder-LeeTao** [wzmsltw/BSN-boundary-sensitive-network#11]
Hello, thank you for your contribution.
In the paper,  _On ActivityNet-1.3, we use top-1 video-level class generated by classification model [44] for all proposals in a video._ ([44] means UTS at ActivityNet 2016). But I can't find the source code.
So my question is how do you actually do action detection with proposals? 
Thank you very much!

**Comment by wzmsltw** [comment]
Hi @coder-LeeTao , we obtain [44]'s result files by e-mail in last year. Recently, I found that these result files may have some problem. Thus we are replacing it with classification results of another solution (CUHK at ActivityNet 2017), and will update our arxiv paper in several days. 
If you also need their classification results for action detection, you can send a email to [CUHK at ActivityNet 2017].
Please feel free to reopen this issue if you have furthur problem.

**Comment by coder-LeeTao** [comment]
Thank you very much @wzmsltw ! I have another question. In the paper, _On THUMOS14, we use top-2 video-level classes generated by UntrimmedNet [43] for proposals generated by BSN and other methods, where multiplication of confidence score and class score is used for retrieving detections._  
My understanding is using <img src="https://latex.codecogs.com/gif.latex?p_f=p_{conf}*p^s*&space;p^e&space;*&space;p_{class1}&space;*&space;p_{class2}" title="p_f=p_{conf}*p^s* p^e * p_{class1} * p_{class2}" /> in NMS retrieval. The proposal is then assigned to the action category with the highest score in UNet.

**Comment by wzmsltw** [comment]
Actually, top-2 means we combine two classes with a proposal separately. So the first proposal result with class_1 has score  p_f = p_{conf} * p^s * p^e * p_{class_1}, and the second proposal result with class_2 has score  p_f = p_{conf} * p^s * p^e * p_{class_2}. And we actually use NMS on proposals first, then combine proposals with action classes.

**Comment by coder-LeeTao** [comment]
Thank you very much@wzmsltw ! So in the final result, is a proposal used twice(with different action class label)?

**Comment by wzmsltw** [comment]
Yes
