### ISSUE TITLE
How to get the results of AR@50, AR@100, AR@200...

### ISSUE THREAD

**Issue by ivyvideo** [wzmsltw/BSN-boundary-sensitive-network#14]
Hi Will,
Could you please tell me how to control the different numbers of proposals **precisely**, e.g. 50, 100, 200?
I know it maybe by setting the threshold, but I have no idea how to do it and make the number of proposals are excatly the amount you want.
Thanks!

**Comment by wzmsltw** [comment]
Hi @ivyvideo , I use interp1d function to get precisely AR@N:

```
from scipy.interpolate import interp1d
f=interp1d(average_nr_proposals,average_recall,axis=0)
print f(50),f(100)
```
