### ISSUE TITLE
Training code for THUMOS14

### ISSUE THREAD

**Issue by fkxssaa** [wzmsltw/BSN-boundary-sensitive-network#15]
Thank you for your contribution.Limited by the computer, I could only do experiments on the small data set THUMOS14.However, there was something I did not understand about the training process of THUMOS14, which caused me to fail to achieve the effect in the paper.For example, the setting of the TEM training set in THUMOS14 (the sliding window size is 100, so how to regularize time for each group) and the extraction of BSP features.
Could you please send the code to me? E-mail: 349249680 @qq.com
Thank you very much!

**Comment by wzmsltw** [comment]
Hi fkxssaa, please refer our paper for details. We have released feature for THUMOS-14, which is extracted using TSN model trained on ActivityNet. You can find previous discussion in https://github.com/wzmsltw/BSN-boundary-sensitive-network/issues/13
