### ISSUE TITLE
Thumos14 features required

### ISSUE THREAD

**Issue by fizamurtaza** [wzmsltw/BSN-boundary-sensitive-network#16]
Hello,

Can you please also provide the rescaled features for Thumos14 similar to ActivityNet dataset?

**Comment by fizamurtaza** [comment]
Thank you.
I think the link you provided has expired.  I am getting this error:

啊哦，你所访问的页面不存在了。
可能的原因：

1.在地址栏中输入了错误的地址。

2.你点击的某个链接已过期。

返回上一级页面>

回到网站首页>

**Comment by fizamurtaza** [comment]
Can you please provide the fresh link?
Thanks in advance.

**Comment by wzmsltw** [comment]
Hi @fizamurtaza, I can still open this link. Can you try again?
link: https://pan.baidu.com/s/1Vj5WITTC8OqrEgJVrZnkKA
password: amjm

**Comment by fizamurtaza** [comment]
Thank you again. 
I am still unable to download it, I think it is because of Baidu...

**Comment by wzmsltw** [comment]
I create a new link without password, you can have a try:

https://pan.baidu.com/s/1SDGuQu08qYeTij6H3NBRgA

**Comment by fizamurtaza** [comment]
Thank you. 
I get this error every time i click on the link:
"https://pan.baidu.com/error/404.html"
Is is possible to upload on Google cloud?

**Comment by fizamurtaza** [comment]
Hello,
Can you tell me why i am having 404 error?

**Comment by wzmsltw** [comment]
I am not sure why you cannot open this link, it is fine in my browser. I will upload it on Google cloud soon.

**Comment by wzmsltw** [comment]
You can download feature from: https://drive.google.com/file/d/1yRvebY46qxP0Sq-YellIktsMFEm1id1A/view?usp=sharing

**Comment by fizamurtaza** [comment]
Many thanks.

**Comment by Scipio1996** [comment]
Hello, THUMOS 2014 page can not found. Can you give me Baidu Yun link? Thank you very much.

**Comment by XiongChengxin** [comment]
@Scipio1996 THUMOS14 website is accessible now.
