### ISSUE TITLE
PEM - sampling the high low and medium

### ISSUE THREAD

**Issue by ilan1987** [wzmsltw/BSN-boundary-sensitive-network#2]
There are some inconsistencies between the paper and the implementation when it comes to sampling data for predicting the iou in the PEM. According to the paper you sample with a 1 to 2 ratio between negative and positives. according to the code, you measure according to the ratio between positive and negatives and according to the ratio between medium and positive. can you add more information about that?
Thanks,
Ilan

**Comment by suhaisheng** [comment]
@ilan1987 ， hello, according to the paper,  we take all positive proposals and randomly sample the proposals in the negative set to insure that the ratio between the two selected sets is nearly 1:2 for data balance. However, we also try to use some proposals of medium set with g_iou in [0.3, 0.7] for training and find that the performance can be further boosted with this setting. Hence in the final implementations, the ratio of selected proposals from these three sets is 1:1:2. Thanks for your interest in our work.
