### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by zjyalice** [wzmsltw/BSN-boundary-sensitive-network#21]
Hi~
When i run the code `python TEM_train.py`, i meet a error about feature,like this:
`IOError:File ./data/activitynet_feature_chunk/csv_mean_100/v_QOlsCBRmfWY.csv does not exit`
I check the  zip_csv_mean_100.zip and cannot find this file...
What's wrong with it? Is it the feature missing?

**Comment by wzmsltw** [comment]
Hi @zjyalice ，I have this file in my folder and the zipfile actually contain this file. Are you unzip correctly?

**Comment by zjyalice** [comment]
> Hi @zjyalice ，I have this file in my folder and the zipfile actually contain this file. Are you unzip correctly?

OMG！I use code unzip to unzip the file,it indeed does not cotain it , but i unzip in windows again, i find this file! Maybe i unzip incorrectly....So stupid... (╥﹏╥)  
So sorry to bother you ！

**Comment by wzmsltw** [comment]
Maybe there are some problem about unzip command, and I am very glad to here everything is ok now.
