### ISSUE TITLE
ValueError: cannot reshape array of size 16 into shape (16,100,newaxis)

### ISSUE THREAD

**Issue by 666zcli** [wzmsltw/BSN-boundary-sensitive-network#22]
Hi Tianwwei,
I download the data from GoogleCloud and when  I ran the TEM_train.py, there is ValueError: cannot reshape array of size 16 into shape (16,100,newaxis). Do i unzip the dataset incorrectly?
Thanks

**Comment by wzmsltw** [comment]
Hi @666zcli , I guess it is an unzip problem, or maybe you can try BaiduYun
