### ISSUE TITLE
Sharing proposals of THUMOS14?

### ISSUE THREAD

**Issue by zijunwei** [wzmsltw/BSN-boundary-sensitive-network#23]
Thanks for sharing your work on github!
Is it possible to share the THUMOS14 proposal results? We do not need the code or model, just a json file with the proposals (video-id, start, end, score) would be fine. We want to compare our proposal methods with this and do some analysis.
Many thanks.

**Comment by wzmsltw** [comment]
Hi @zijunwei , please tell me your email address.

**Comment by zijunwei** [comment]
Hi the email address is zijwei@cs.stonybrook.edu. Many thanks

**Comment by hongsong-wang** [comment]
Could you also send me the proposals. My email address is hongsongsui@gmail.com. Thanks!

**Comment by wzmsltw** [comment]
Hi @hongsong-wang , have sent. Please check your mailbox.

**Comment by LeavesLei** [comment]
Hi, Tianwei Lin, I am a senior student form Beihang University. I plan to study BSN as my bachelor thesis. Could you sent me the dasaset result after two-stream-network. My email is leishiye@gmail.com. Thank you!

**Comment by wzmsltw** [comment]
@LeavesLei have sent

**Comment by zjyalice** [comment]
Hi~Tianwei Lin , could you send me the proposals about THUMOS14 ? My email address is 1286014974@qq.com. Thank you very much and best whishes!

**Comment by wzmsltw** [comment]
@zjyalice have sent

**Comment by xinyeCH** [comment]
Hi, Tianwei LIn, could you also send me the proposals of THUMOS14? My mail address is xinye136@gmail.com. Thanks very much!

**Comment by wzmsltw** [comment]
@yinianjimo  have sent

**Comment by yklilfft** [comment]
Hi, Tianwei LIn, would u please send THUMOS14 proposals ? My mail address is yk.li@siat.ac.cn. Thanks very much!

**Comment by pranavgundewar** [comment]
Hi Tianwei Lin, could you please send THUMOS'14 proposals to my email address- pranavgundewar@gmail.com?

Thank you so much for great work and sharing the codebase.

**Comment by Lechatelia** [comment]
Hi, Tianwei Lin.  I am a student from  Xi'an Jiaotong Unversity,  and could you also send me the proposals of THUMOS14? My email is lechatelia@stu.xjtu.edu.cn. thanks!

**Comment by Jockey721** [comment]
Hi, Tianwei LIn @wzmsltw  , i tried to reproduce the experiment on THUMOS14, but the performance (AR@100 from ) is only 37%. Could you also send me the proposals of THUMOS14 foranalysis? My mail address is 812618101@qq.com. Thanks very much!

**Comment by jojojo-h** [comment]
Hi, Tianwei LIn, would u please send THUMOS14 proposals ? My mail address is 2994056113@qq.com. Thanks very much!
