### ISSUE TITLE
Could we get C3D features for THUMOS'14?

### ISSUE THREAD

**Issue by GGQ1996** [wzmsltw/BSN-boundary-sensitive-network#24]
Hi Tianwei,
Thanks for your great work！ Can you provide the C3D features for THUMOS14？It would be great if the original features for THUMOS'14 are provided. Thanks!

**Comment by wzmsltw** [comment]
link: https://pan.baidu.com/s/1UMQ0PMcEQfpsEKKtWSHiaw 
code: v83b

**Comment by leemengxing** [comment]
I want to know the details of feature extraction in C3d. Can you provide？thanks very much.

**Comment by pengjinqiang** [comment]
Why the features you provided are of dimension 487. I think it would be either 200 or 400, but why 487. What is the meaning of 487. @wzmsltw 
-------------------------------------------------------------
I found that 487 is the number of the category of Sports-1M. So, the C3D features of THUMOS14 are extracted by C3D model pretrained on Sports-1M? But in your paper, the C3D features of THUMOS14 are extracted by C3D model pretrained on UCF-101, as below. 

> Thus, for fair comparison, we train BSN with feature extracted by C3D network [35] pre-trained on UCF-101 dataset, then perform Greedy-NMS and Soft-NMS on C3D-BSN and original 2Stream-BSN respectively. 

So, which one did you use for extracting C3D feature of THUMOS14?
Expect your reply!
