### ISSUE TITLE
question about action detection performance on activity-net

### ISSUE THREAD

**Issue by shiyi001** [wzmsltw/BSN-boundary-sensitive-network#27]
Hello, Tianwei~ I tried to reimplement your action detection experiments on activity-net, but only get a poor result. Here is my results using different iou thresh on NMS:

| IOU thresh | map@0.5 | map@0.75 | map@0.95 | average |
| :---------: | :---------: | :---------: | :----------: | :-------: |
| 0.3 | 0.450 | 0.274 | 0.078 |  0.281  |
| 0.4 | 0.455 | 0.280 | 0.078 | 0.287  |
| 0.5 | 0.450 | 0.288 | 0.078 | 0.292  |
| 0.6 | 0.437 | 0.298 | 0.079 | 0.293  |
| 0.7 | 0.422 | 0.304 | 0.080 | 0.291  |

I found average number of proposals is far smaller than 100. Does it matter?

I have checked my code several times, but can not find any mistake. Can you help me? Or share your code which generates the detection result. Many thanks.

**Comment by wzmsltw** [comment]
Hi @shiyi001 , please refer results on our updated paper (my homepage and arxiv), where BSN reach 30.03 average mAP. Thus your results seens close.
Please leave your email and I will sent your code.

**Comment by shiyi001** [comment]
My email is i_am_shiyi@163.com. Many thanks again.

**Comment by PeisenZhao** [comment]
Hi  Tianwei,
I also try to reimplement your action detection experiments on activity-net 1.3.
Can you send me your code which generates the detection result? 
pszhao@sjtu.edu.cn
Many thanks.

**Comment by Zhuysheng** [comment]
@shiyi001 @wzmsltw @PeisenZhao  Hi, Could you send me a copy, my email is  yszhu@nuist.edu.cn. Many thanks.

**Comment by semchan** [comment]
Hi, Tianwei,
would you pls send it to me? thanks. 380003859@qq.com

**Comment by ciwei123** [comment]
@shiyi001 @wzmsltw @PeisenZhao @semchan Would you please send the code which generates the detection result to me? 2606789239@qq.com Thank you very much!

**Comment by zhuolinumd** [comment]
@shiyi001 @wzmsltw @PeisenZhao @semchan @ciwei123 

Can you share the detection code with me? 10432110@qq.com Thank you so much.

**Comment by pengjinqiang** [comment]
@shiyi001 @wzmsltw @PeisenZhao @semchan @ciwei123 
Could you please send me the same code? 343400575@qq.com Thanks!

**Comment by PawnGeek** [comment]
@shiyi001 @wzmsltw @PeisenZhao @semchan @ciwei123
Could you please send me the same code? 349354604@qq.com Thanks!

**Comment by maodong2056** [comment]
@wzmsltw @shiyi001 @semchan @PeisenZhao @jiang2764 Could you share the detection code and results with me?273270145@qq.com Thanks!

**Comment by immaping** [comment]
@wzmsltw @shiyi001 @PeisenZhao @semchan @jiang2764 Would you please send the code which generates the detection result to me? lee55777@163.com Thank you very much!

**Comment by liuheng92** [comment]
@wzmsltw @shiyi001 @PeisenZhao @semchan @jiang2764 Can you share the detection code with me? 1041017843@qq.com, Thx!

**Comment by hanielwang** [comment]
@wzmsltw @shiyi001 @PeisenZhao @semchan @jiang2764 Can you share the detection code with me? Thanks. 302747091@qq.com

**Comment by NooneOnlyOne** [comment]
@wzmsltw @AmorTila @shiyi001 @PeisenZhao @jiang2764 @semchan Could you share the detection code with me? 
1584450964@qq.com  ,   Thank you very much!

**Comment by lucky-23** [comment]
@wzmsltw @shiyi001 @liuheng92 @jiang2764 @semchan could you please share the detection code with me ? I have been stuck on the action detection for many days .My email is lkeisham23@gmail.com. Thank you very much!
