### ISSUE TITLE
HOW about THUMOS2014 result?

### ISSUE THREAD

**Issue by cc786537662** [wzmsltw/BSN-boundary-sensitive-network#3]
this repo will get ActivityNet v1.3 result according to your README,but in your paper,we can also  see THUMOS2014 result, so could you please release some pre-trained model on THUMOS2014 dataset?
I believe the model in ./models/TEM or PEM is pre-trained model on ActivityNet ?

**Comment by wzmsltw** [comment]
Hi, we are not plan to release code or model for thumos-14 yet.
