### ISSUE TITLE
Excuse me,where's the video_info_csv?

### ISSUE THREAD

**Issue by zys20172212265** [wzmsltw/BSN-boundary-sensitive-network#33]
https://github.com/wzmsltw/BSN-boundary-sensitive-network/blob/f13707fbc362486e93178c39f9c4d398afe2cb2f/data/activitynet_feature_cuhk/data_process.py#L48

**Comment by wzmsltw** [comment]
Hi @zys20172212265 , this file is in data/activitynet_annotations
