### ISSUE TITLE
About THUMOS14 annotations

### ISSUE THREAD

**Issue by yklilfft** [wzmsltw/BSN-boundary-sensitive-network#36]
Hi tianwei!
    Thanks a lot about BSN code release.
    I tried to train BSN on THUMOS14, do u have annotations of THUMOS14 used in BSN training procedure?

**Comment by wzmsltw** [comment]
HI @yklilfft You can leave you email than I can send you thumos codes and files.

**Comment by yklilfft** [comment]
Thanks a lot! My email address is 727627725@qq.com

**Comment by PeisenZhao** [comment]
@wzmsltw @yklilfft Can you share the same code and files of THUMOS14 with me? Thanks a lot!
pszhao@sjtu.edu.cn

**Comment by PeisenZhao** [comment]
pszhao@sjtu.edu.cn

**Comment by EscargotXJ** [comment]
@wzmsltw @yklilfft I also want to get the code and files of THUMOS14. Could you share one with me? Thanks a lot! My email address is 1336742850@qq.com

**Comment by Qinying-Liu** [comment]
@wzmsltw @yklilfft Can you share the code and files of THUMOS14 with me? My email is  1258168813@qq.com

**Comment by zaie** [comment]
@wzmsltw @yklilfft Can you share the code and files of THUMOS14 with me? My email is zliu62@buffalo.edu

**Comment by wzmsltw** [comment]
@zaie @canbaoburen @EscargotXJ 
[BSN_share.zip](https://github.com/wzmsltw/BSN-boundary-sensitive-network/files/3802733/BSN_share.zip)

**Comment by doudou123456** [comment]
@yklilfft Can you share the same code and files of THUMOS14 with me? Thanks a lot! My email is 804641065@qq.com
