### ISSUE TITLE
question about PGM

### ISSUE THREAD

**Issue by Zhuysheng** [wzmsltw/BSN-boundary-sensitive-network#37]
https://github.com/wzmsltw/BSN-boundary-sensitive-network/blob/f13707fbc362486e93178c39f9c4d398afe2cb2f/PGM_proposal_generation.py#L50
1.why set the start_bins[[0,-1]]=1
2.when i try to reimplement the experiment on thumos14 by pytorch, the results are not good, how to set the parameters like the tem_training_lr, tem_weight_decay in TEM
3.how to do action detection based on the generated proposals

**Comment by wzmsltw** [comment]
Hi @Zhuysheng , Acutally set start_bins[0] = 1 is enough...

**Comment by wzmsltw** [comment]
You can leave you email then I can send you BSN-thumos codes.

**Comment by Zhuysheng** [comment]
@wzmsltw thanks, my email address is 1072094108@qq.com

**Comment by wzmsltw** [comment]
@Zhuysheng  have sent

**Comment by Qinying-Liu** [comment]
@Zhuysheng @wzmsltw Can you share the code and files of THUMOS14 with me? My email is 1258168813@qq.com

**Comment by doudou123456** [comment]
@Zhuysheng Can you share the same code and files of THUMOS14 with me? Thanks a lot! My email is 804641065@qq.com

**Comment by doudou123456** [comment]
@Zhuysheng @wzmsltw Thank you a lot. Recently, our research group is following your work. If you can share the code and files of THUMOS14 with us, it will be convenient for us to do comparative experiments. My email is 804641065@qq.com

**Comment by Rui-hue** [comment]
@Zhuysheng @wzmsltw Can you share the code and files of THUMOS14 with me? My email is 645249607@qq.com

**Comment by Rui-hue** [comment]
@Zhuysheng @wzmsltw Can you share the code and files of THUMOS14 with me? My email is 645249607@qq
.com
