### ISSUE TITLE
ERROR about activitynet dataset

### ISSUE THREAD

**Issue by ivyvideo** [wzmsltw/BSN-boundary-sensitive-network#4]
Hi, thanks for your great contribution!
However I have two questions while I am downloading the dataset activitynet-1.3 as follows:
1. It shows that some of the youtube accountis terminated so the video is not available either. ![1](https://user-images.githubusercontent.com/42105211/45005810-13abb280-b028-11e8-8a68-5fb0b7919710.png)
2. Due to some unknown reasons, the video is unable to extract, also the webpage cannot be reached.
![2](https://user-images.githubusercontent.com/42105211/45005813-14dcdf80-b028-11e8-95be-4ad2ea5916e7.png)

Now I have downloaded just 18449 videos, and I notice that there are 19228 csv files instead of original 19994. So we could not download them all, right?

**Comment by cc786537662** [comment]
I got the same issus here, and I only get 17721 videos from youtube instead, and I think this happens due to the absence of those links in youtueb website.

**Comment by wzmsltw** [comment]
Hi

There are actuallly many videos un-available  since some video may be deleted by author. Actually, I only downlowned 19228 videos last year. So  I think you can upload a file containing the list of missing video, and I can upload missing videos.

**Comment by coder-LeeTao** [comment]
Hi,
Thank you for your contribution! I only get 18408 videos. I made a json file to record the data that I was missing. @wzmsltw 
[unload_videos.zip](https://github.com/wzmsltw/BSN-boundary-sensitive-network/files/2395157/unload_videos.zip)

**Comment by wzmsltw** [comment]
Hi all
I have uploaded missing videos (those I have)  in Baidu Yun Disk, based on @coder-LeeTao 's list.

链接: https://pan.baidu.com/s/1DcifxIAijSe7C-jQx5KuMA
提取码: 6txk

**Comment by cc786537662** [comment]
same issue here，I have downloaded the common missing part videos between mine and coder-LeeTao's , but I still missing around 1400 videos ,
[missing.txt](https://github.com/wzmsltw/BSN-boundary-sensitive-network/files/2404238/missing.txt)
