### ISSUE TITLE
400-d vectors in csv_mean_100.csv file

### ISSUE THREAD

**Issue by ivyvideo** [wzmsltw/BSN-boundary-sensitive-network#5]
Hi, as you mentioned in the paper, **RGB** and **optical flow** features are extracted by two-stream network. 
So I am wondering what is the meaning of 400-d vector in .csv file?
Are they ordered? For example, the first 200-d means RGB feature and the rest means optical?

**Comment by wzmsltw** [comment]
Hi

The first 200-d feature  are RGB feature and the rest are optical-flow feature. They are simply concated.
