### ISSUE TITLE
How to classify generated proposals using UNet?

### ISSUE THREAD

**Issue by xlliu7** [wzmsltw/BSN-boundary-sensitive-network#6]
As described in your paper, you perform action detection by classifying proposals using Untrimmed Net or SCNN. I am trying to do this with UntrimmendNet but don't know how.
Can you provide more details? Do I need to re-train UntrimmedNet based on BSN generated proposals or the "shots" described in the UntrimmedNet paper?  And how about testing? What are the inputs and outputs?

**Comment by wzmsltw** [comment]
Hi, we use UNet trained on UCF-101 to generate video-level classification results for testing videos, then use video-level class as the class of all proposals in this testing video.
And for SCNN, we use pre-trained model ( released by Shou Zheng) to directly classify the generated proposals.

**Comment by xlliu7** [comment]
Hi Tianwei
Thanks for your response. How about proposals of ActivityNet? In your paper, I notice that you use the method referenced as "UTS at ActivityNet 2016". I found this method uses MFCC, iDT features for ensemble, which is quite complicated and time-consuming. Do you actually conduct the original method for classification? Can you share the video-level classification scores? Thanks!

**Comment by wzmsltw** [comment]
Hi @xlliu7 , we obtain [44]'s result files by e-mail in last year. Recently, I found that these result files may have some problem. Thus we are replacing it with classification results of another solution (CUHK at ActivityNet 2017), and will update our arxiv paper in several days.
If you also need their classification results for action detection, you can send a email to [CUHK at ActivityNet 2017].
Please feel free to reopen this issue if you have furthur problem.
