### ISSUE TITLE
Could I get original TSN features?

### ISSUE THREAD

**Issue by Pilhyeon** [wzmsltw/BSN-boundary-sensitive-network#7]
Hello,

I'm trying to experiment with this model using original features.
But I'm in trouble of acquiring video features from "CUHK & ETH & SIAT Solution to ActivityNet Challenge 2016" model.
I want to get the original features used in your paper. (2048-dim I think, and whose length is not rescaled to 100)
Will you able to provide the 2048-dim original two stream features not rescaled?

Thank you.

**Comment by wzmsltw** [comment]
Hi Pilhyeon

During feature extraction, we use "fc-action" layer, so the dimension of feature is 400 ( 200 + 200). I will upload feature zip file days later.

**Comment by wzmsltw** [comment]
Hi Pilhyeon

I am uploading original feature in BaiduYun: 

链接: https://pan.baidu.com/s/1871KzGL0KlVCgTBpMf_sag 
提取码: h9st

The uploading procedure will finish in one or two hours. Please feel free to reopen the issue if you have furthur question.

**Comment by cominger** [comment]
Hello, @wzmsltw 
First of all, Thanks to uploading the original feature!
However, downloading the file from Baidu Yun required the Baidu account.
Could you able to re-upload the same file to google drive for non-Badiu users?

Thank you

**Comment by wzmsltw** [comment]
Hi @cominger , I am sorry that my google cloud disk does not has enough space for the feature. So you can sign up a baidu account or can you find any free net-disk?

**Comment by wduo** [comment]
Hi! Tianwei,@wzmsltw 
I have the following questions I would like to ask you.

1. When I extract the features of the 'fc-action' layer, I get the feature size (25, 10, 200), where 25 is the num_frame_per_video parameter in tsn. What does 10 mean? In the feature extraction process, did you set num_frame_per_video to the total number of frames in the video?
2. In the readData function of the data_process.py file, how do I get the CSV format features in the spatial_dir and temporal_dir folders?
In the poolData function of the data_process.py file, what is the difference between the num_prop parameter and the num_frame_per_video parameter in tsn?
3. How do I get the 100*400 features for the TEM module?

Thank you very much! Looking forward to your reply!

**Comment by wduo** [comment]
@wzmsltw 
About question 1, the link of eval_net.py here: https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py
Should I save the 'frame_scores' of line92 to a separate CSV file (a video corresponds to a CSV file)?

About question 2，the link of data_process.py here: https://github.com/wzmsltw/BSN-boundary-sensitive-network.pytorch/blob/master/data/activitynet_feature_cuhk/data_process.py

Wish you a good time！

**Comment by zys20172212265** [comment]
@wduo do you solve the problem?

**Comment by 95xueqian** [comment]
@zys20172212265 have you solved the problem? thanks

**Comment by wduo** [comment]
@zys20172212265 Solved.

**Comment by zys20172212265** [comment]
@wduo Since im just getting started in this filed , Could you show me more details about your question 3

**Comment by xianguo-dev** [comment]
> @zys20172212265 Solved.

Hi! I'm confused about how to extract feature for every snippet? Does it mean that I need to use every snippet(16 frames as Tianwei do)as input of TSN? And  the score of snippets is the output(feature)?
