### ISSUE TITLE
step in extracting frames from video

### ISSUE THREAD

**Issue by ZENGXH** [wzmsltw/BSN-boundary-sensitive-network#9]
Hi Tianwei,

I would like to ask for the `-s`(step) setting you used in [this command](https://github.com/yjxiong/temporal-segment-networks/blob/2a496535b91515ccb7537327230ceaf30645eced/tools/build_of.py#L52).

Did you change the `-s 1` to `-s 8` or `-s 16`? If not, how do you skip the sampling of frames? 

Thanks! ;)

**Comment by wzmsltw** [comment]
Hi @ZENGXH , I did not use optical flow codes from cuhk. I use https://github.com/feichtenhofer/gpu_flow for flow extraction.
And for here, actually I think "-s 1" should be used. During extracting feature on ActivityNet, we set each 16 frames as a snippet, and we calculate 5 frames using 6 consecutive frames in the middle of snippet. Thus it should be -s 1.
